table dCliente
	lineageTag: a15c1633-9828-4da5-b699-b3336d4faacd

	column ID_Cliente
		dataType: string
		isHidden
		lineageTag: 8574de12-00af-4714-a6e0-fe3862f951b9
		summarizeBy: none
		sourceColumn: ID_Cliente

		annotation SummarizationSetBy = Automatic

	column Cliente
		dataType: string
		lineageTag: 280e5590-5de6-46dc-9c6f-8c90e010bd93
		summarizeBy: none
		sourceColumn: Cliente

		annotation SummarizationSetBy = Automatic

	column Segmento
		dataType: string
		lineageTag: 316ce4be-9ba8-4305-87bd-9215e0d3f785
		summarizeBy: none
		sourceColumn: Segmento

		annotation SummarizationSetBy = Automatic

	column Canal
		dataType: string
		lineageTag: edde0714-169f-4ca8-a4e0-0280201bf509
		summarizeBy: none
		sourceColumn: Canal

		annotation SummarizationSetBy = Automatic

	column Porte
		dataType: string
		lineageTag: 558e1e9d-d712-4f56-9afc-7632cade3ff8
		summarizeBy: none
		sourceColumn: Porte

		annotation SummarizationSetBy = Automatic

	column UF_Cliente
		dataType: string
		lineageTag: ec1fa6f9-8eae-4b92-9738-1cd3dea55159
		dataCategory: StateOrProvince
		summarizeBy: none
		sourceColumn: UF_Cliente

		annotation SummarizationSetBy = Automatic

	column Cidade_Cliente
		dataType: string
		lineageTag: a945bc5c-4ed5-449c-b155-77a197434a63
		dataCategory: City
		summarizeBy: none
		sourceColumn: Cidade_Cliente

		annotation SummarizationSetBy = Automatic

	column Data_Cadastro
		dataType: dateTime
		formatString: dd/mm/yyyy
		lineageTag: 32a4e738-2068-407a-9ab2-de06f0ee9ce7
		summarizeBy: none
		sourceColumn: Data_Cadastro

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Prazo_Pagamento
		dataType: string
		lineageTag: db834376-4398-4483-a48a-ac9051b08afb
		summarizeBy: none
		sourceColumn: Prazo_Pagamento

		annotation SummarizationSetBy = Automatic

	partition dCliente = m
		mode: import
		queryGroup: 03_Dimensões
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\isaqu\Documents\Projeto Matheus\PROJETO LOGISTICA\Dimensoes_Logistica.xlsx"), null, true),
				    dCliente_Sheet = Source{[Item="dCliente",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(dCliente_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID_Cliente", type text}, {"Cliente", type text}, {"Segmento", type text}, {"Canal", type text}, {"Porte", type text}, {"UF_Cliente", type text}, {"Cidade_Cliente", type text}, {"Data_Cadastro", type date}, {"Prazo_Pagamento", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

