table dVeiculo
	lineageTag: c8d3433a-59c3-4033-9536-2b589a0b4f94

	column ID_Veiculo
		dataType: string
		isHidden
		lineageTag: 10d07b42-1f01-4539-b6b0-782b85345bbf
		summarizeBy: none
		sourceColumn: ID_Veiculo

		annotation SummarizationSetBy = Automatic

	column Placa
		dataType: string
		lineageTag: 8fce8cfd-2118-48da-978c-4a01458395d6
		summarizeBy: none
		sourceColumn: Placa

		annotation SummarizationSetBy = Automatic

	column Tipo_Veiculo
		dataType: string
		lineageTag: 353d7d39-a3d2-4223-a4e1-2135471de052
		summarizeBy: none
		sourceColumn: Tipo_Veiculo

		annotation SummarizationSetBy = Automatic

	column Capacidade_KG
		dataType: int64
		formatString: 0
		lineageTag: b702888e-cdfb-4ac9-b5e9-1c1ee149486a
		summarizeBy: none
		sourceColumn: Capacidade_KG

		annotation SummarizationSetBy = Automatic

	column Capacidade_M3
		dataType: int64
		formatString: 0
		lineageTag: 615c85ae-4e67-4253-bf3e-1d8a025dca9b
		summarizeBy: none
		sourceColumn: Capacidade_M3

		annotation SummarizationSetBy = Automatic

	column Ano_Fabricacao
		dataType: int64
		formatString: 0
		lineageTag: 7832f9c6-ef57-4b7d-8d5d-351e90b57d19
		summarizeBy: none
		sourceColumn: Ano_Fabricacao

		annotation SummarizationSetBy = Automatic

	column Combustivel
		dataType: string
		lineageTag: 780789e6-e357-4d72-bf8e-37e7255894ac
		summarizeBy: none
		sourceColumn: Combustivel

		annotation SummarizationSetBy = Automatic

	column ID_Transportadora_Veiculo
		dataType: string
		isHidden
		lineageTag: 043561df-218e-4604-9fe5-740391d6b0e0
		summarizeBy: none
		sourceColumn: ID_Transportadora_Veiculo

		annotation SummarizationSetBy = Automatic

	column Custo_Padrao_KM
		dataType: double
		lineageTag: 3493c4f2-556d-4b4b-a9ca-b6356c2642e9
		summarizeBy: none
		sourceColumn: Custo_Padrao_KM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition dVeiculo = m
		mode: import
		queryGroup: 03_Dimensões
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\isaqu\Documents\Projeto Matheus\PROJETO LOGISTICA\Dimensoes_Logistica.xlsx"), null, true),
				    dVeiculo_Sheet = Source{[Item="dVeiculo",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(dVeiculo_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID_Veiculo", type text}, {"Placa", type text}, {"Tipo_Veiculo", type text}, {"Capacidade_KG", Int64.Type}, {"Capacidade_M3", Int64.Type}, {"Ano_Fabricacao", Int64.Type}, {"Combustivel", type text}, {"ID_Transportadora_Veiculo", type text}, {"Custo_Padrao_KM", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

