table fMetas
	lineageTag: 39d150e7-d287-414a-b7cd-d93c4821fda9

	column ID_CD
		dataType: string
		isHidden
		lineageTag: a2804382-a538-40d2-8b7a-f84f0e4c26ee
		summarizeBy: none
		sourceColumn: ID_CD

		annotation SummarizationSetBy = Automatic

	column Ano_Mes
		dataType: dateTime
		formatString: Long Date
		lineageTag: a782040f-4aba-4f52-8dcd-35e08bd6f7e1
		summarizeBy: none
		sourceColumn: Ano_Mes

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: cefd15c6-a171-46b7-ae32-21776983bdb0
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mes
		dataType: int64
		formatString: 0
		lineageTag: fb304fd8-ec4c-4cf1-b13d-b527a684d9ec
		summarizeBy: sum
		sourceColumn: Mes

		annotation SummarizationSetBy = Automatic

	column Meta_OTIF
		dataType: double
		lineageTag: a5cc32f4-a353-4233-a948-b091793345dd
		summarizeBy: sum
		sourceColumn: Meta_OTIF

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Meta_Custo_por_KM
		dataType: double
		lineageTag: 993fc6a1-cb01-4fd1-aa2b-ea086d3442cc
		summarizeBy: sum
		sourceColumn: Meta_Custo_por_KM

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Meta_Entregas
		dataType: int64
		formatString: 0
		lineageTag: 3487fd3e-609a-4768-ae97-e7249e475e14
		summarizeBy: sum
		sourceColumn: Meta_Entregas

		annotation SummarizationSetBy = Automatic

	partition fMetas = m
		mode: import
		queryGroup: 02_Fatos
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\isaqu\Documents\Projeto Matheus\PROJETO LOGISTICA\Dimensoes_Logistica.xlsx"), null, true),
				    fMetas_Sheet = Source{[Item="fMetas",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(fMetas_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID_CD", type text}, {"Ano_Mes", type date}, {"Ano", Int64.Type}, {"Mes", Int64.Type}, {"Meta_OTIF", type number}, {"Meta_Custo_por_KM", type number}, {"Meta_Entregas", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

